- name: Add NGINX repository
  yum_repository:
    name: nginx
    description: Nginx YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    enabled: yes
    gpgcheck: no

- name: Install Nginx
  yum:
    name: nginx
    state: present
