- hosts: mwlab
  #gather_facts: false
  become: true
  strategy: free
  roles:
    - { role: ../roles/inetsim }

- hosts: targets
  #gather_facts: false
  become: true
  strategy: free
  roles:
    - { role: ../roles/nginx }
